---
- name: copy Xauthority script
  ansible.builtin.copy:
      src: /home/ubuntu/Xauthocjeck.sh
      dest: /home/ubuntu/Xauthocjeck.sh
      owner: ubuntu
      group: ubuntu
      mode: '0755'

- name: copy the script of installing containerd and dependencies and kuberenetes
  ansible.builtin.copy:
      src: /home/ubuntu/containerDandDepKube.sh
      dest: /home/ubuntu/containerDandDepKube.sh
      owner: ubuntu
      group: ubuntu
      mode: '0755'

- name: Run shell script on remote server
  shell: sh /home/ubuntu/Xauthocjeck.sh

- name: Run shell script on remote server
  shell: sh /home/ubuntu/containerDandDepKube.sh


- name: Remove shell script from remote server
  file:
    path: /home/ubuntu/Xauthocjeck.sh
    state: absent

- name: Remove shell script from remote server
  file:
    path: /home/ubuntu/containerDandDepKube.sh
    state: absent
