---
- name: Generate the token in master node
  command: sudo kubeadm token create --print-join-command
  register: join_command_output

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command_output.stdout }}"

- name: Debug the join command and display the output on screen
  debug:
    var: join_command_output.stdout
